<?php
/** @var $block \Rissc\Printformer\Block\Custom\Editor\Link */

$quoteItem = $block->getQuoteItem();
$product = $block->getProduct();
$editorLink = $block->getEditorOpenLink();
$printformerBlock = $block->getPrintformerBlock();

$quoteItemId = $quoteItem->getId();
?>
<br />
<div id="printformer_draftid_<?php echo $quoteItemId; ?>" style="width: max-content">
    <button id="openEditor" href="<?php echo $editorLink; ?>" class="pf-link"><?php echo __('Open Editor');?></button>
    <div id="info">
        <br /><span>Draft ID: </span> <a href="<?php echo $block->getDraftURL($quoteItem->getPrintformerDraftid()) ?>"> <?php echo $quoteItem->getPrintformerDraftid(); ?></a>
        <br /><button id="copy"><?php echo __('Copy Draft ID'); ?></button>
        <?php //Textarea for coping the draft id ?>
        <textarea id="draftID" style="display: none"><?php echo $quoteItem->getPrintformerDraftid(); ?></textarea>
    </div>
    <?php if ($block->isOrdered($quoteItem, $quoteItem->getPrintformerDraftid())): ?>
        <a class="action-default scalable action-save action-secondary" href="<?php echo $block->getPdfUrl($quoteItem); ?>" target="_blank">
            <?php echo __('Show print file'); ?>
        </a>
    <?php endif; ?>
</div>

<div class="printformer-editor-main"
     id="printformer-editor-main_<?php echo $quoteItemId; ?>"
     title="<?php echo $product->getName(); ?>">
</div>
<div id="printformer-editor-close_<?php echo $quoteItemId; ?>">
    <p><?php echo __($printformerBlock->getCloseNoticeText()); ?></p>
</div>
<?php if($printformerBlock->isFormatChangeNotice()): ?>
    <div id="printformer-editor-notice_<?php echo $quoteItemId; ?>">
        <p><?php echo __($printformerBlock->getFormatNoticeText()); ?></p>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    <?php echo json_encode([
            '#printformer_draftid_' . $quoteItemId => [
                'Rissc_Printformer/js/custom-printformer' => [
                    'editBtnSelector'       => '#printformer_draftid_' . $quoteItemId . ' .pf-link',
                    'editorMainSelector'    => '#printformer-editor-main_' . $quoteItemId,
                    'editorCloseSelector'   => '#printformer-editor-close_' . $quoteItemId,
                    'editorNoticeSelector'  => '#printformer-editor-notice_' . $quoteItemId,
                    'productTitle' => $product->getName()
                ]
            ]
        ]);
    ?>
</script>

<script>
    require(['jquery', 'jquery/ui', 'domReady!'], function($){
        var copyBtn = $('#copy');

        //copy the draft id on button click event
        copyBtn.click(function (event) {
            var draftID = $('#draftID');
            draftID.css('display', 'block');
            draftID.select();

            try {
                document.execCommand('copy');
            } catch(err) {
                console.log('Copying was unsuccessful');
            }
            draftID.css('display', 'none');
        });

    });
</script>