<?php
$_data = array(
    "Edit draft" => __('Edit draft'),
    "You've made two Drafts. Please select the one you want to add to cart." => __('You\'ve made two Drafts. Please select the one you want to add to cart.'),
    "draft-editor" => __('draft-editor'),
    "draft-upload" => __('draft-upload'),
    'View draft' => __('View draft'),
    'View upload' => __('View upload')
);
?>
<script type="text/javascript">
    require(["jquery","mage/translate"], function($){
        $.mage.translate.add(<?php echo Zend_Json::encode($_data) ?>)
    });
</script>