<?php
/**
 * @var $block \Rissc\Printformer\Block\Catalog\Product\View\Preselect
 */
?>
<script type="text/javascript">
    require(['jquery', 'printformerTools', 'domReady!'], function($) {
        $(window).on('load', function() {
            <?php
            $jsonOptions = json_encode([
                'currentProduct' => $block->getProduct()->getId()
            ]);
            ?>

            $('#product-addtocart-button, #product-updatecart-button').printformerTools(<?php echo $jsonOptions; ?>)
                .sessionData()
                .getSavedEditorCalls('<?php echo $block->getDraftsGetUrl(); ?>');

            var preselectButtons = $('.printformer-preselect');
            $.each(preselectButtons, function (i, elem) {
                <?php
                $jsonOptions = json_encode([
                    'saveUrl' => $block->getOptionsSaveUrl(),
                    'currentProduct' => $block->getProduct()->getId()
                ]);
                ?>

                $(preselectButtons[i]).printformerTools(<?php echo $jsonOptions; ?>)
                    .preselect()
                    .initButton();
            });
        });
        $(document).on('pricemodelListLoaded', function(){
            <?php
                $opt = [
                    'optionsUrl' => $block->getOptionsGetUrl(),
                    'preselected' => ($block->isOnConfigurePDS() ? $block->getPreselection() : []),
                    'currentProduct' => $block->getProduct()->getId()
                ];
            ?>

            $(this).printformerTools(<?php echo json_encode($opt); ?>)
                .preselect()
                .getPreselectedOptions();
        });
    });
</script>