<?php
/**
 * @var $block \Rissc\Printformer\Block\Catalog\Product\View\Preselect
 */
?>
<script type="text/javascript">
    require(['domReady!', 'jquery', 'printformerTools'], function(domReady, $, pfTools){
        <?php
        $jsonOptions = json_encode([
            'currentProduct' => $block->getProduct()->getId()
        ]);
        ?>
        var sessionTools = new pfTools($('#product-addtocart-button, #product-updatecart-button'), 'session', <?php echo $jsonOptions; ?>);
        sessionTools.getSavedEditorCalls('<?php echo $block->getDraftsGetUrl(); ?>');

        var preselectButtons = $('.printformer-preselect');
        $.each(preselectButtons, function (i, elem) {
            <?php
            $jsonOptions = json_encode([
                'saveUrl' => $block->getOptionsSaveUrl(),
                'currentProduct' => $block->getProduct()->getId()
            ]);
            ?>

            var preselectTools = new pfTools($(preselectButtons[i]), 'preselect', <?php echo $jsonOptions; ?>);
            preselectTools.initButton();
        });
        <?php
        $opt = [
            'optionsUrl' => $block->getOptionsGetUrl(),
            'preselected' => ($block->isOnConfigurePDS() ? $block->getPreselection() : []),
            'currentProduct' => $block->getProduct()->getId()
        ];
        ?>
        $(document).on('pricemodelListLoaded', function () {
            if (!isConfigure) {
                // var preselectTools = new pfTools($(this), 'preselect', <?php // echo json_encode($opt); ?>);
                // preselectTools.getPreselectedOptions();
            }
        });
    });
</script>