<?php
/** @var \Rissc\Printformer\Block\Catalog\Product\View\Printformer $block */
$block->cleanupDraftSession();
$product = $block->getProduct();
?>

<?php if ($product->isSalable()): ?>
    <div class="printformer-actions box-tocart <?php if ($product->getTypeId() === 'downloadable'): ?>product-options-bottom<?php endif; ?>">
        <?php foreach ($block->getCatalogProductPrintformerProducts($product->getId(), $product->getStoreId()) as $_catalogProductPrintformerProduct): ?>
            <?php $_printformerProduct = $_catalogProductPrintformerProduct->getPrintformerProduct() ?>
            <button id="printformer-button-<?php echo $_printformerProduct->getId() ?>"
                    type="button"
                    data-pf-masterid="<?php echo $_printformerProduct->getMasterId(); ?>"
                    data-pf-type="editor"
                    data-pf-intent="<?php echo $_printformerProduct->getIntent(); ?>"
                    class="printformer-preselect action primary tocart printformer-button <?php echo $block->getButtonCss($_catalogProductPrintformerProduct) ?>"
                    disabled="disabled">
                <span><?php echo __($block->getButtonText()) ?></span>
            </button>
            <?php if ($block->canShowDeleteButton()): ?>
                <button id="printformer-delete-<?php echo $_printformerProduct->getId() ?>"
                        data-printformer-product="<?php echo $_printformerProduct->getId() ?>"
                        data-printformer-master="<?php echo $_printformerProduct->getMasterId(); ?>"
                        data-product-id="<?php echo $product->getId(); ?>"
                        class="action primary tocart printformer-delete"
                        disabled="disabled"
                        style="display: none"></button>
                <div id="printformer-delete-confirm-<?php echo $_printformerProduct->getId() ?>"
                     style="display: none">
                    <p><?php echo __($block->getDeleteConfirmText()); ?></p>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>

    <div id="printformer-editor-main" style="text-align: center; display: flex" title="<?php echo $product->getName() ?>">
    </div>
    <div id="printformer-editor-close" style="display: none">
        <p><?php echo __($block->getCloseNoticeText()) ?></p>
    </div>
    <?php if ($block->isFormatChangeNotice()): ?>
        <div id="printformer-editor-notice">
            <p><?php echo __($block->getFormatNoticeText()) ?></p>
        </div>
    <?php endif; ?>
<?php endif; ?>