<?php
/** @var \Rissc\Printformer\Block\Catalog\Product\View\Printformer $block */
$block->cleanupDraftSession();
?>

<?php if($block->getProduct()->isSalable()): ?>
    <?php foreach($block->getPrintformerProducts() as $_printformerProduct): ?>
        <div class="printformer-actions box-tocart">
            <button id="printformer-button-<?php echo $_printformerProduct->getId() ?>"
                    type="button"
                    data-pf-masterid="<?php echo $_printformerProduct->getMasterId(); ?>"
                    data-pf-type="editor"
                    data-pf-intent="<?php echo $_printformerProduct->getIntent(); ?>"
                    class="printformer-preselect action primary tocart <?php echo $block->getButtonCss() ?>"
                    disabled="disabled">
                <?php if($_printformerProduct->getIntent() == 'upload' || $_printformerProduct->getIntent() == 'upload-and-editor'): ?>
                    <span><?php echo __('Upload') ?></span>
                <?php else: ?>
                    <span><?php echo __($block->getButtonText()) ?></span>
                <?php endif; ?>
            </button>
        </div>
    <?php endforeach; ?>

    <div id="printformer-editor-main" title="<?php echo $block->getProduct()->getName() ?>">
    </div>
    <div id="printformer-editor-close">
        <p><?php echo __($block->getCloseNoticeText()) ?></p>
    </div>
    <?php if ($block->isFormatChangeNotice()): ?>
        <div id="printformer-editor-notice">
            <p><?php echo __($block->getFormatNoticeText()) ?></p>
        </div>
    <?php endif; ?>
<?php endif;?>