<?php
/** @var \Rissc\Printformer\Block\Catalog\Product\View\Printformer $block */
$_hasCapability = $block->isUploadProduct() || $block->isEditorProduct() || $block->isPersonalizationProduct() || $block->isUploadAndEditorProduct();
?>

<?php if($block->getProduct()->isSalable() && $_hasCapability): ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "printformer": {}
            }
        }
    </script>
<?php endif; ?>

<script type="text/javascript">
    var globalPrintformerOptions = '<?php echo $block->getPreselection(); ?>';
    var printformerInstance = null;
</script>