<?php
/** @var \Rissc\Printformer\Block\Catalog\Product\View\Printformer $block */ ?>
<?php
if ($block->getProduct()->isSalable()): ?>
    <script type="text/javascript">
        var printformerInstance = null;

    </script>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "printformer": <?php
        echo $block->getJsonConfig(); ?>
            }
        }

    </script>
<?php
endif; ?>
