<?php
/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Edit */
?>
<?php if ($block->isProductVisibleInSiteVisibility()): ?>
    <a class="action action-edit"
       href="<?php /* @escapeNotVerified */ echo $block->getConfigureUrl() ?>"
       title="<?php echo $block->escapeHtml(__($this->getEditItemText())); ?>">
        <span>
            <?php /* @escapeNotVerified */ echo __($this->getEditItemText()) ?>
        </span>
   </a>
<?php endif ?>
